### ISSUE TITLE
taco_test crashes in Release build

### ISSUE THREAD

**Issue by Infinoid** [tensor-compiler/taco#287]
Should the test suite pass for Release builds?  It crashes on my machine.

cmake command: `cmake -DCMAKE_BUILD_TYPE=Release ../taco`
cmake version 3.17.1
gcc (Ubuntu 7.5.0-3ubuntu1\~18.04) 7.5.0
libc6-dev 2.27-3ubuntu1
libstdc++-7-dev 7.5.0-3ubuntu1\~18.04

output:
```
[----------] 15 tests from scheduling_eval
[ RUN      ] scheduling_eval.test_spmvCPU_temp
[       OK ] scheduling_eval.test_spmvCPU_temp (403 ms)
[ RUN      ] scheduling_eval.example_spmvCPU_splitpos
Segmentation fault (core dumped)
```

backtrace:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  std::__shared_ptr<taco::Iterator::Content, (__gnu_cxx::_Lock_policy)2>::operator bool (this=0x20) at /usr/include/c++/7/bits/shared_ptr_base.h:1261
1261	      { return _M_ptr == 0 ? false : true; }
(gdb) bt
#0  std::__shared_ptr<taco::Iterator::Content, (__gnu_cxx::_Lock_policy)2>::operator bool (this=0x20) at /usr/include/c++/7/bits/shared_ptr_base.h:1261
#1  std::operator!=<taco::Iterator::Content>(std::shared_ptr<taco::Iterator::Content> const&, decltype(nullptr)) (__a=...)
    at /usr/include/c++/7/bits/shared_ptr.h:389
#2  taco::Iterator::defined (this=0x20) at /home/infinoid/workspace/taco/taco/src/lower/iterator.cpp:323
#3  0x00007f3142d7c631 in taco::Iterator::isRoot (this=this@entry=0x7ffd231da810) at /home/infinoid/workspace/taco/taco/src/lower/iterator.cpp:82
#4  0x00007f3142db50c8 in taco::LowererImpl::searchForFusedPositionStart (this=0x555ee50032b0, forall=..., posIterator=...)
    at /home/infinoid/workspace/taco/taco/src/lower/lowerer_impl.cpp:608
```

Looks like a NULL pointer to me.  Note the `(this=0x20)` in frame `#2`.

This crash happens with or without `-DCUDA=ON`.  RelWithDebInfo builds pass the tests fine, this crash only happens in Release builds.  I added `-g -ggdb` by hand to get a better backtrace.

**Comment by Infinoid** [comment]
The full backtrace is here if you need it:
https://gist.github.com/Infinoid/f61d07957f464e8bf8324c7ee6fba11c
